### ISSUE TITLE
Failed to create backup in Docker

### ISSUE THREAD

**Issue by Aragur** [pocketbase/pocketbase#3089]
The Backup functionality isn't working on my instance.
Using the latest version of Pocketbase and Docker.

`--debug`-Log shows the following:
```
blob (key "pb_backup_20230808092633.zip") (code=Unknown): rename /tmp/pb_backup_20230808092633.zip.17795e46db5a7b21.tmp /pb_data/backups/pb_backup_20230808092633.zip: invalid cross-device link
```

**Comment by ganigeorgiev** [comment]
I think this was fixed in v0.16.3+. What version of PocketBase do you use?

**Comment by Aragur** [comment]
I'm using 0.17.2

**Comment by ganigeorgiev** [comment]
Hm, what was fixed before was the restore functionality (see https://github.com/pocketbase/pocketbase/issues/2519) but I forgot to check the backup.

I'll test it sometime later today and will try to submit a fix.

**Comment by ganigeorgiev** [comment]
Should be fixed in [PocketBase v0.17.3](https://github.com/pocketbase/pocketbase/releases/tag/v0.17.3).

If the above doesn't resolve your issue please provide more details about your Docker setup and I'll try to investigate it further.

**Comment by Aragur** [comment]
@ganigeorgiev still the same issue after upgrading to v0.17.3.

### My Docker-Compose file
```yaml
services:
  example-server:
    restart: always
    image: private-image
    command: ["/server", "serve", "--http=0.0.0.0:8090", "--debug"]
    volumes:
      - ./data:/pb_data:rw
```

### My Dockerfile
```Dockerfile
## Build
FROM golang:1.20-buster as build

WORKDIR /app

COPY server/go.mod ./
COPY server/go.sum ./
COPY server/pkg ./pkg
RUN go mod download

COPY server/*.go ./

RUN CGO_ENABLED=1 go build -o /server

## Deploy
FROM gcr.io/distroless/base-debian10

WORKDIR /

COPY --from=build /server /server
COPY webapp/dist /webapp

EXPOSE 8090

ENTRYPOINT ["/server", "serve", "--http=0.0.0.0:8090"]
```

**Comment by ganigeorgiev** [comment]
I guess the `tmp` directory errors during "upload" could happen if the `pb_data` volume is a separate disk partition, I'm not really sure.

As a workaround you can try to mount the `/tmp` dir as the special temp `pb_data/.pb_temp_to_delete` directory (or another directory from the same volume/partition), aka. something like:

```
- ./data/.pb_temp_to_delete:/tmp
```

**Comment by ganigeorgiev** [comment]
See the note in [`go-cloud/blob` package](https://github.com/google/go-cloud/blob/cfe20caf3c31547c3be443e0196d4086462a7c43/blob/fileblob/fileblob.go#L18-L24) that we use for the file uploads (including the backups):

> // To avoid partial writes, fileblob writes to a temporary file and then renames
// the temporary file to the final path on Close. By default, it creates these
// temporary files in `os.TempDir`. If `os.TempDir` is on a different mount than
// your base bucket path, the `os.Rename` will fail with `invalid cross-device link`.
// To avoid this, **either configure the temp dir to use by setting the environment
// variable `TMPDIR`, or set `Options.NoTempDir` to `true`** (fileblob will create
// the temporary files next to the actual files instead of in a temporary directory).

**Comment by ganigeorgiev** [comment]
On further investigation, it seems that the `NoTempDir` option was added just couple days ago (see https://github.com/google/go-cloud/pull/3295). The [related issue](https://github.com/google/go-cloud/issues/3294) is also very similar to yours.

As mentioned in the previous comment, I'll consider updating the dependency and enabling the option (_I'll have to find a way to reproduce it somehow first_), but as a workaround for now try to set the `TMPDIR` env variable.

**Comment by ganigeorgiev** [comment]
> What should I set `TMPDIR` to?

To a directory path that is inside your mounted dir, aka. in your case I guess it could be `/pb_data/.pb_temp_to_delete` or some other directory that shares the same mount point.

**Comment by Aragur** [comment]
Thanks this worked for me

**Comment by Aragur** [comment]
@ganigeorgiev Just wanted to ask for an update.
Furthermore, I experienced issues, when restarting the docker container.
After it is restarted, the `/pb_data/.pb_temp_to_delete`-directory is deleted and has to be created manually.

**Comment by khrome83** [comment]
@ganigeorgiev this still appears to be some type of issues.

I get this same error message in the ui, but this outcome. 

`failed to create a temp dir: mkdir pb_data/.pb_temp_to_delete: operation not permitted`

Pocketbase version - [PocketBase v0.18.6](https://github.com/pocketbase/pocketbase/releases)

What advice do you have for giving Pocketbase permission to make the directory?

I thought about just adding it in the docker image, but after running that night, it would be deleted. 

Suggestions?

**Comment by ganigeorgiev** [comment]
@khrome83 The above "cross-device link" error shouldn't exist anymore with the latest release.

I have no idea why the above is causing a file permission error.
Make sure that your volume is mounted with the correct path.

If you are not able to resolve it, please consider filing a new Q&A discussion with more details about your setup and I'll try to investigate it.

**Comment by khrome83** [comment]
Done! See https://github.com/pocketbase/pocketbase/discussions/3385
