### ISSUE TITLE
"More" button on collection edit screen is not keyboard accessible

### ISSUE THREAD

**Issue by ndarilek** [pocketbase/pocketbase#4607]
In the collection editor, I am attempting to activate the button with the ARIA label "More" via the keyboard, but nothing seems to happen. Tried with both Space and Enter, and on Firefox and Chrome.

I'm a screen reader user, and tried a few additional tricks to simulate a mouse click on the button. None of them worked either, which is odd.

This is on V0.22.5. Please let me know if I can provide any additional details to help debug this.

**Comment by ganigeorgiev** [comment]
I'm able to open the collection "More" dropdown by navigating with the keyboard with Tab and Enter/Spacebar but there seems to be some issue (maybe with the focusout event) that prevents selecting an item from the "More" dropdown. I'll try to investigate it sometime later today.

**Comment by ganigeorgiev** [comment]
I've push in `master` small change that should fix the keyboard navigation for the dropdown menus.

I want to experiment with some performance optimization in relation to https://github.com/pocketbase/pocketbase/discussions/4612#discussioncomment-8881219 so I'll not rush a release, but the change will be available with the next minor v0.22.6 release (most likely at the beginning of next week).

If you want to test it, you can try building the example main.go from the `master` branch:

1. [Install Go 1.21+](https://go.dev/doc/install) (if you haven't already)
2. Download/clone the PocketBase repo
   ```sh
   git clone https://github.com/pocketbase/pocketbase.git
   ```
3. Navigate to `examples/base` directory.
4. Run `go build`
5. Start the generated executable: `./base serve`

**Comment by ganigeorgiev** [comment]
The recent changes are available as part [v0.22.6 release](https://github.com/pocketbase/pocketbase/releases/tag/v0.22.6).

If you are still experiencing issues, feel free to elaborate how you are testing and I'll try to investigate it further.

**Comment by ndarilek** [comment]
Sorry for not following up quicker. This bug still exists but I know what's going on. Here's the HTML I get when clicking the button and inspecting the element:

```
<div tabindex="0" role="button" aria-label="More collection options" class="btn btn-sm btn-circle btn-transparent flex-gap-0 active"><i class="ri-more-line" aria-hidden="true"></i> <div class="toggler-container" tabindex="-1" role="menu"><div class="dropdown dropdown-right m-t-5 active" style=""><button type="button" class="dropdown-item" role="menuitem"><i class="ri-file-copy-line" aria-hidden="true"></i> <span class="txt">Duplicate</span></button> <button type="button" class="dropdown-item txt-danger" role="menuitem"><i class="ri-delete-bin-7-line" aria-hidden="true"></i> <span class="txt">Delete</span></button></div></div></div>
```

Looks like clicking the button adds the menu as a child of the button itself. Unfortunately this isn't accessible, because screen readers generally make assumptions about whether or not to present something based on widget semantics, and buttons generally don't have children. They may cause a menu or nearby element to appear, but that element wouldn't be a child of the button.

Fixing this should just be a matter of moving this menu, and any others like this, outside of the element with the button role so my screen reader will notice it. There's more work to be done but this would make it easier to discover.

I can probably poke at this in a couple weeks but can't guarantee I won't break styling or the visual appearance. But moving this menu to a sibling of the button should be all that's needed.

Thanks.

**Comment by ganigeorgiev** [comment]
Hm, I can't find any information related to this. Navigating using the keyboard with tab + space/enter works for me.

Could you elaborate what screenreader software you are using so that I can try to reproduce it locally?

In general we rely on the relative position of the dropdown and cannot move it easily out of the button. I'll consider it with the [planned Admin UI rewrite in the near future](https://github.com/pocketbase/pocketbase/discussions/4355) but there are no fixed ETAs.

**Comment by ganigeorgiev** [comment]
@ndarilek I've just tested it with the official [Chrome screen reader plugin](https://chromewebstore.google.com/detail/screen-reader/kgejglhpjiefppelpmljglcjbhoiplfn) and the "tab + enter/space" navigation works correctly for me in the latest version.

As mentioned above, I'll consider moving the dropdowns out of the "role=button" element with the planned refactoring but until there are more details how to reproduce it locally I'm not sure how to help and I'll close the issue for now.
