### ISSUE TITLE
Using expand on two nested relationships only expands the second one.

### ISSUE THREAD

**Issue by jeffmikels** [pocketbase/pocketbase#586]
In my database, I have four collections: `households` `children` `allergies` `rooms`.

- `household` records have a relation to a list of `children` records.
- `child` records have a relation to a list of `allergies` records under the field `allergies` and a relation to a single `room` record under the field `last_room`.

If I make a request for households and attempt to expand children, children.allergies, and children.last_room, I do not get children.allergies in the response:

I use this api request (Dart):

```dart
var results = await client.records.getFullList(households, query: {'expand': 'children,children.allergies,children.last_room'});
```

Here's the result I get for the first record:

```json
{
  "id": "slynlPhz9DnYUmU",
  "created": "2022-09-19 20:04:10.634",
  "updated": "2022-09-19 20:04:15.135",
  "@collectionId": "DNxV8vh6pZ4kIsA",
  "@collectionName": "households",
  "@expand": {
    "children": [
      {
        "@collectionId": "Q8oiRIdggscAUuU",
        "@collectionName": "children",
        "@expand": {
          "last_room": {
            "@collectionId": "p4n6EUPpFyMQ8iU",
            "@collectionName": "rooms",
            "allow_checkin": true,
            "created": "2022-09-17 21:56:45.287",
            "description": "Toddlers (walking - 2yrs) gather in the Park to relax and play while learning about how God created them to know him and to know his love.",
            "id": "TTySaDbguzeiwgG",
            "maximum_age": 3,
            "minimum_age": 1,
            "name": "The Park",
            "updated": "2022-09-17 21:56:45.287"
          }
        },
        "allergies": [
          "800H3lkLif1iryd",
          "oFl6HJoUSdeu1Eb",
          "sGnuMedIWI3FFsW",
          "TlYxyfk5THuuq8x",
          "XZfNcgFNCObYBAU"
        ],
        "birthdate": "2022-09-19 16:04:12.247",
        "created": "2022-09-19 20:04:12.284",
        "first_name": "TEST",
        "household": "slynlPhz9DnYUmU",
        "id": "vUclZAyQbW0Oxml",
        "last_name": "MIKELS",
        "last_room": "TTySaDbguzeiwgG",
        "parent_note": "",
        "photo_url": "REDACTED",
        "updated": "2022-09-19 20:04:12.284"
      },
      {
        "@collectionId": "Q8oiRIdggscAUuU",
        "@collectionName": "children",
        "@expand": {
          "last_room": {
            "@collectionId": "p4n6EUPpFyMQ8iU",
            "@collectionName": "rooms",
            "allow_checkin": true,
            "created": "2022-09-17 21:56:45.287",
            "description": "Toddlers (walking - 2yrs) gather in the Park to relax and play while learning about how God created them to know him and to know his love.",
            "id": "TTySaDbguzeiwgG",
            "maximum_age": 3,
            "minimum_age": 1,
            "name": "The Park",
            "updated": "2022-09-17 21:56:45.287"
          }
        },
        "allergies": [
          "XZfNcgFNCObYBAU"
        ],
        "birthdate": "2022-09-19 16:04:13.255",
        "created": "2022-09-19 20:04:13.268",
        "first_name": "TESTY",
        "household": "slynlPhz9DnYUmU",
        "id": "YzDra7DLkwcccgD",
        "last_name": "TESTERSON",
        "last_room": "TTySaDbguzeiwgG",
        "parent_note": "",
        "photo_url": "REDACTED",
        "updated": "2022-09-19 20:04:13.268"
      },
      {
        "@collectionId": "Q8oiRIdggscAUuU",
        "@collectionName": "children",
        "@expand": {
          "last_room": {
            "@collectionId": "p4n6EUPpFyMQ8iU",
            "@collectionName": "rooms",
            "allow_checkin": true,
            "created": "2022-09-17 21:56:45.287",
            "description": "Toddlers (walking - 2yrs) gather in the Park to relax and play while learning about how God created them to know him and to know his love.",
            "id": "TTySaDbguzeiwgG",
            "maximum_age": 3,
            "minimum_age": 1,
            "name": "The Park",
            "updated": "2022-09-17 21:56:45.287"
          }
        },
        "allergies": [
          "FoiNIKSr2ZrQdVl",
          "oFl6HJoUSdeu1Eb",
          "xIA4JPgpGOvJycH"
        ],
        "birthdate": "2022-09-19 16:04:14.264",
        "created": "2022-09-19 20:04:14.273",
        "first_name": "TESTER",
        "household": "slynlPhz9DnYUmU",
        "id": "KTATOMznFh8BEtU",
        "last_name": "TWO",
        "last_room": "TTySaDbguzeiwgG",
        "parent_note": "",
        "photo_url": "REDACTED",
        "updated": "2022-09-19 20:04:14.273"
      }
    ]
  },
  "address": "REDACTED",
  "cell_phone_1": "REDACTED",
  "cell_phone_2": "",
  "children": [
    "vUclZAyQbW0Oxml",
    "YzDra7DLkwcccgD",
    "KTATOMznFh8BEtU"
  ],
  "city": "REDACTED",
  "email": "REDACTED",
  "household_name": "REDACTED",
  "photo_url": "REDACTED",
  "state": "REDACTED",
  "zip": "REDACTED"
}
```

Note that in the `@expand` element for each child, only the `last_room` relationship is expanded. If I make the same request without `children.last_room`, then I properly get the allergies expanded.

**Comment by ganigeorgiev** [comment]
This looks like a bug. I'll check it sometime later today and will update the integration tests to verify it.

**Comment by ganigeorgiev** [comment]
@jeffmikels Thanks for reporting the issue. It indeed ended up a bug (we were overwriting the already expanded items). This is fixed in `master` now. The integration tests were also updated to check the scenario when there are multiple nested relations with shared base path.

_This will be included with the next bugfix release (v0.7.6) sometime later this week._

**Comment by FlixMa** [comment]
I am experiencing a similar problem on v0.10.1 (also tested with v0.8 and v0.9.2).
Can you confirm, that this issues still persists for 'deeper' expands like `a.b.c1, a.b.c2`?
To me it seems, as c2 is not available (at least according to the network tab).

**Comment by ganigeorgiev** [comment]
@FlixMa I'm not able to reproduce the issue. As mentioned in the comments above, an integration test was also added to confirm that it is working correctly.

Please make sure that all your expanded rel collections have the correct **View API rule** access.

If you are still experiencing issues, please open a new discussion/issue with details about your collections and how you are sending the request.

**Comment by ganigeorgiev** [comment]
@FlixMa Actually, on second read, you may be right that the bug still persist. The test doesn't check duplicated nested rel paths. I'll update the tests a little later this evening.

**Comment by FlixMa** [comment]
I was about to submit a new issue, when I read your response :-)
So here are my findings:

I created a fresh new instance of pocketbase v0.10.1 with the following dummy schema:
```json
[
    {
        "id": "_pb_users_auth_",
        "name": "users",
        "type": "auth",
        "system": false,
        "schema": [
            {
                "id": "users_name",
                "name": "name",
                "type": "text",
                "system": false,
                "required": false,
                "unique": false,
                "options": {
                    "min": null,
                    "max": null,
                    "pattern": ""
                }
            },
            {
                "id": "users_avatar",
                "name": "avatar",
                "type": "file",
                "system": false,
                "required": false,
                "unique": false,
                "options": {
                    "maxSelect": 1,
                    "maxSize": 5242880,
                    "mimeTypes": [
                        "image/jpg",
                        "image/jpeg",
                        "image/png",
                        "image/svg+xml",
                        "image/gif"
                    ],
                    "thumbs": null
                }
            }
        ],
        "listRule": "",
        "viewRule": "",
        "createRule": "",
        "updateRule": "id = @request.auth.id",
        "deleteRule": "id = @request.auth.id",
        "options": {
            "allowEmailAuth": false,
            "allowOAuth2Auth": true,
            "allowUsernameAuth": true,
            "exceptEmailDomains": null,
            "manageRule": null,
            "minPasswordLength": 12,
            "onlyEmailDomains": null,
            "requireEmail": false
        }
    },
    {
        "id": "eqau93sefom3i34",
        "name": "start",
        "type": "base",
        "system": false,
        "schema": [
            {
                "id": "othhsiln",
                "name": "name",
                "type": "text",
                "system": false,
                "required": false,
                "unique": false,
                "options": {
                    "min": null,
                    "max": null,
                    "pattern": ""
                }
            },
            {
                "id": "zdu8hx9h",
                "name": "inter_a",
                "type": "relation",
                "system": false,
                "required": false,
                "unique": false,
                "options": {
                    "maxSelect": 1,
                    "collectionId": "mhw68zkfjzaeo63",
                    "cascadeDelete": false
                }
            }
        ],
        "listRule": "",
        "viewRule": "",
        "createRule": null,
        "updateRule": null,
        "deleteRule": null,
        "options": {}
    },
    {
        "id": "mhw68zkfjzaeo63",
        "name": "intermediate_A",
        "type": "base",
        "system": false,
        "schema": [
            {
                "id": "z1dxqnba",
                "name": "name",
                "type": "text",
                "system": false,
                "required": false,
                "unique": false,
                "options": {
                    "min": null,
                    "max": null,
                    "pattern": ""
                }
            },
            {
                "id": "zktgirsz",
                "name": "inter_b",
                "type": "relation",
                "system": false,
                "required": false,
                "unique": false,
                "options": {
                    "maxSelect": 1,
                    "collectionId": "shoc2oghz2n77tp",
                    "cascadeDelete": false
                }
            }
        ],
        "listRule": "",
        "viewRule": "",
        "createRule": null,
        "updateRule": null,
        "deleteRule": null,
        "options": {}
    },
    {
        "id": "shoc2oghz2n77tp",
        "name": "intermediate_B",
        "type": "base",
        "system": false,
        "schema": [
            {
                "id": "rmmuubev",
                "name": "name",
                "type": "text",
                "system": false,
                "required": false,
                "unique": false,
                "options": {
                    "min": null,
                    "max": null,
                    "pattern": ""
                }
            },
            {
                "id": "d5nle0ct",
                "name": "dest_c1",
                "type": "relation",
                "system": false,
                "required": false,
                "unique": false,
                "options": {
                    "maxSelect": 1,
                    "collectionId": "bvbqygurhpzvc9l",
                    "cascadeDelete": false
                }
            },
            {
                "id": "si1jat3s",
                "name": "dest_c2",
                "type": "relation",
                "system": false,
                "required": false,
                "unique": false,
                "options": {
                    "maxSelect": 1,
                    "collectionId": "s7wz3rexyljwqv4",
                    "cascadeDelete": false
                }
            }
        ],
        "listRule": "",
        "viewRule": "",
        "createRule": null,
        "updateRule": null,
        "deleteRule": null,
        "options": {}
    },
    {
        "id": "bvbqygurhpzvc9l",
        "name": "destination_C1",
        "type": "base",
        "system": false,
        "schema": [
            {
                "id": "a7ycjsr9",
                "name": "name",
                "type": "text",
                "system": false,
                "required": false,
                "unique": false,
                "options": {
                    "min": null,
                    "max": null,
                    "pattern": ""
                }
            }
        ],
        "listRule": "",
        "viewRule": null,
        "createRule": null,
        "updateRule": null,
        "deleteRule": null,
        "options": {}
    },
    {
        "id": "s7wz3rexyljwqv4",
        "name": "destination_C2",
        "type": "base",
        "system": false,
        "schema": [
            {
                "id": "0lreoiwh",
                "name": "name",
                "type": "text",
                "system": false,
                "required": false,
                "unique": false,
                "options": {
                    "min": null,
                    "max": null,
                    "pattern": ""
                }
            }
        ],
        "listRule": "",
        "viewRule": "",
        "createRule": null,
        "updateRule": null,
        "deleteRule": null,
        "options": {}
    }
]
```

Using the provided javascript sdk, the following request

```js
const response = await pocketbase.collection('start').getList(1, 10, {
    expand: 'inter_a.inter_b.dest_c2,inter_a.inter_b.dest_c1'
})
```

returns:

```json
{
  "page": 1,
  "perPage": 10,
  "totalItems": 1,
  "totalPages": 1,
  "items": [
    {
      "collectionId": "eqau93sefom3i34",
      "collectionName": "start",
      "created": "2022-12-19 15:21:32.645Z",
      "expand": {
        "inter_a": {
          "collectionId": "mhw68zkfjzaeo63",
          "collectionName": "intermediate_A",
          "created": "2022-12-19 15:20:35.953Z",
          "expand": {
            "inter_b": {
              "collectionId": "shoc2oghz2n77tp",
              "collectionName": "intermediate_B",
              "created": "2022-12-19 15:20:22.265Z",
              "dest_c1": "d4p8kad1336h5d0",
              "dest_c2": "wp4itxvzhv452sm",
              "expand": {
                "dest_c2": {
                  "collectionId": "s7wz3rexyljwqv4",
                  "collectionName": "destination_C2",
                  "created": "2022-12-19 15:19:55.455Z",
                  "id": "wp4itxvzhv452sm",
                  "name": "London ",
                  "updated": "2022-12-19 15:19:55.455Z"
                }
              },
              "id": "krm72ui0opahzur",
              "name": "Paris",
              "updated": "2022-12-19 15:20:22.265Z"
            }
          },
          "id": "lt1958gzo1gop2l",
          "inter_b": "krm72ui0opahzur",
          "name": "Rome",
          "updated": "2022-12-19 15:20:35.953Z"
        }
      },
      "id": "yj2zlcwcm6ow2ya",
      "inter_a": "lt1958gzo1gop2l",
      "name": "Home",
      "updated": "2022-12-19 15:21:32.645Z"
    }
  ]
}
```

I am not able to find a way to alter the `expand` in a way, that it actually returns both `dest_c1` and `dest_c2`.
Hope this helps!

**Comment by ganigeorgiev** [comment]
@FlixMa Sorry for the delay and thank you for providing more details.

The nested expansion should be fixed in the latest [v0.10.2 release](https://github.com/pocketbase/pocketbase/releases/tag/v0.10.2). I've updated the integration tests and this time I also added an unit test to just check the recursive expansion.
Please let me know if you stumble on something else and I'll investigate it.

**Comment by FlixMa** [comment]
I appreciate the quick response and I’m happy to confirm that it works on my side.

**Comment by vinyll** [comment]
Hey there, that's a very useful feature and I'm glad as a new user to see this implemented.
It should very much be documented how to expand multiple fields as an intuitive way would have been to `{ expand: ['rel1', 'rel2'] }`.
Being a string with comma is very fine as well and should probably appear somewhere :)

Thanks for this nice job 🚀
